apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kagent
resources:
  - external-secret.yaml
  - mcp-deploy.yaml
  - remotemcpserver.yaml
  - skills-configmap.yaml
  - sandboxagent.yaml
